apiVersion: v1
kind: ConfigMap
metadata:
    name: game-ini
    namespace: insurgency-sandstorm
data:
  Game.ini: |
    [/Script/Insurgency.INSMultiplayerMode]
    bAutoRecordReplaysDedicated=True
    bHandleDedicatedServerReplays=True
    bSupplyGainEnabled=True
    bAwardSupplyInstantly=True
    MaximumSupply=999
    InitialSupply=30
    RoundLimit=3
    MinimumPlayers=1
    SupplyGainFrequency=99999

    [/Script/Engine.GameNetworkManager]
    bMovementTimeDiscrepancyDetection=False
    bMovementTimeDiscrepancyResolution=False
    ;There is a config option for “ClientAuthorativePosition” on the GameNetworkManager that changes the rules: the server will accept client movement as authoritative and not force a correction if it’s within a squared distance (MAXPOSITIONERRORSQUARED) from where the server last saw it.
    ;So in this case, the server would warp the character to where the client tried to move, and the client’s position is the authority. The server can still replicate movement to the client normally, this just handles rogue client movements.
    ;Can set True on COOP servers
    ClientAuthorativePosition=True
    ;Average size of replicated move packet (ServerMove() packet size) in bytes from player contains client movement and view info
    MoveRepSize=512.0f
    ;is the bandwidth cost in bytes of sending a client adjustment update. 180 is greater than the actual cost, but represents a tweaked value reserving enough bandwidth for other updates sent to the client.
    ;Increase this value to reduce client adjustment update frequency, or if the amount of data sent in the clientadjustment() call increases
    CLIENTADJUSTUPDATECOST=512.0f

    [/Script/Engine.GameSession]
    MaxPlayers=16
    MaxSpectators=0

    [/Script/Insurgency.INSCoopMode]
    MinimumEnemies=3
    MaximumEnemies=24

    MaxPlayersToScaleEnemyCount=10
    bBotsUseHumanLoadouts=False
    bRestrictClassByPlayerLevel=True

    [/ScaleBotAmount/Mutators/ScaleBotAmount.ScaleBotAmount_C]
    ;Enable enemy bot scale for bBots
    bScaleBot=True

    ;;Enemy bot scale base on your friendly bot too. Otherwise, just players
    bScaleWithFriendlyBot=False

    ;;Your team will lose only if your whole team is dead (including friendly bot) with no reinforcement wave left
    ;;You will still lose if enemy recap your checkpoint because that part of the gamemode
    bLoseWhenWholeTeamDead=True

    [/AdvancedSupplyPoints/Mutators/AdvancedSupplyPoints.AdvancedSupplyPoints_C]
    ;Players that captured the objective will get this amount of supply as a reward
    ObjectiveCapturedSupply=7
    ;
    ;;Players that destroyed the objective will get this amount of supply as a reward
    ObjectiveDestroyedSupply=7
    ;
    ;;Everytime a round end, players in losing team will get this amount of supply point
    RoundEndSupply=12
    ;
    ;;Everytime a round end, players in winning team will get this amount of supply point
    RoundEndWinningTeamSupply=7

    [/ImprovedAI/Mutators/ImprovedAI.ImprovedAI_C]
    bEnableBotSkillCfg=True

    ;Distance from this sound that we confirm our target is an enemy
    HearAwareDistanceRadial=3000.0
    HearAwareDistanceGunshot=5000.0
    HearAwareDistanceSprintFootstep=2000.0

    ;Distance from this sound that we can hear the target
    HearDistanceFootstepsSprinting=2500.0
    HearDistanceFootstepsRunning=1000.0

    ;Time before we start attacking at close targets
    AttackDelayClose=0.3

    ;Time before we start attacking at distant targets
    AttackDelayDistant=1.0

    ;Multiplier applied to spotting chance
    ChanceSprintMultiplier=2.0
    ChangeMovingMultiplier=1.20

    AccuracyMultiplier=1.25

    ;Multiply our spread by this much when fully suppressed
    SuppressionAccuracyMultiplier=0.7

    bFindCover=True
    CoverTick=5.0
    bFindCoverWhenShotAt=True
    bCustomBotNames=True

    BotNameList=Mikee,Arc,DaraDef,AniCator,Guinevere,sswires,Circleus,John Doe,Jeroen,fatherHank

    [/WelcomeMessage/Mutators/WelcomeMessage.WelcomeMessage_C]
    ;Message to display to the client when they first spawn in
    WelcomeMessage=%name%, Welcome to my server!/nEnjoy and have fun!

    [/JoinLeaveMessage/Mutators/JoinLeaveMessage.JoinLeaveMessage_C]
    ;Enable or disable join message
    bEnableJoinMessage=True
    ;;Message to appear when a player joins
    JoinMessage=%name% has joined the game.

    ;;Enable or disable leave message
    bEnableLeaveMessage=True
    ;;Message to appear when a player leaves
    LeaveMessage=%name%  has left the game.

    [/ISMCm/Mutators/ISMCarmory_Legacy.ISMCarmory_Legacy_C]
    ;Use to limit Team Leader slots
    NumTeamLeader=-1
    ;Use to enable Medic slots. Names are "Blufor Medic""Redfor Medic" for Legacy and "BF Medic""RF Medic" for other theaters.
    ;Medic slots have no medic functionality and require you to configure another mod to provide it such as @Medic-demo
    NumMedic=0

    ;Tags are appended to gamestate to unlock certain gear. These two variables read from the array TagProfiles if not empty. Otherwise they use a default set (shown in the override example below)
    ;The night profile tags will have the default profile tags appended in night scenarios.
    TagProfileName="ISMCDefault"
    NightTagProfileName="ISMCDefaultNight"
    ;Add this variable multiple times to add multiple profiles. BY DEFAULT THIS IS EMPTY.
    ;Format is =ProfileName:Tag1,Tag2 etc
    ;Current tags available are ISMCNight and Thermal
    TagProfiles="ISMCDefault:"
    TagProfiles="ISMCDefaultNight:ISMCNight"

    ;In addition to adding "Thermal" to a profile above, thermals require hot bodies and players to be drawn to a separate depth buffer for the effect to work. 
    ;This setting needs to be set to "True" for that to be applied. This can affect performance on ALL clients even when thermals aren't in use.
    ;This buffer is also used by the NWI optics shader and will be seen as a wallhack effect on vanilla scopes. ISMC scopes are patched to use a workaround shader but there may still be traces of vanilla scopes in the theaters.
    EnableThermalBuffers=False

    ;Enable/Disable firesupport options for PLAYERS. 0 or 1
    ;Security Vanilla=1
    EnableFS_ArtilleryHE=1
    EnableFS_Apache=1
    EnableFS_ArtillerySmoke=1
    EnableFS_BlackHawk=1
    EnableFS_A10=1

    ;Insurgents Vanilla
    EnableFS_MortarHE=1
    EnableFS_MortarSmoke=1
    EnableFS_MortarChemical=1
    EnableFS_DroneIED=1
    EnableFS_RocketBarrage=1
    EnableFS_DroneGrenade=1

    ;ISMC West
    EnableFS_A10Strafe=1
    EnableFS_A10Strike=1
    EnableFS_AH64=1
    EnableFS_UH60=1
    EnableFS_Harrier=1
    EnableFS_BuggyUS=1
    EnableFS_MRAP=1

    ;ISMC East
    EnableFS_SU25Strafe=1
    EnableFS_SU25Strike=1
    EnableFS_MI17=1
    EnableFS_MI24=1
    EnableFS_YAK38=1
    EnableFS_BUGGYRU=1
    EnableFS_TIGR=1

    ;When using the 3 cosmetic theaters and hardcore checkpoint, by default all gear is stripped from players resulting in invisible players.
    ;An alternative respawn loadout is available to provide a default player model until resupply.
    [/script/insurgency.INSCheckpointHardcoreGameMode]
    RespawnLoadoutsDataAssetPath="/ISMCm/Game/Data/Gamemodes/HardcoreCheckpoint_Loadouts_ISMC.HardcoreCheckpoint_Loadouts_ISMC"
    ;Alternatively you can disable the weapon strip feature.
    bStripWeaponsOnRespawn=False

    [/MoreAmmo/Mutators/MoreAmmo.MoreAmmo_C]
    ;You will get 3 times the normal amount of ammo for your primary weapon.
    PrimaryAmmoMultiplier=3.0
    ;You will get double the normal amount of ammo for your secondary weapon.
    SecondaryAmmoMultiplier=2.0
    ;You will get 50% more ammo for your underbarrel attachment.
    UnderbarrelAmmoMultiplier=1.5
    ;You will get twice the ammo for your explosive launchers like the RPG7/M3 MAAWS, single-use launchers are unaffected
    ExplosiveLauncherAmmoMultiplier=2.0

