apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name  }}
  namespace: {{ .Release.namspace }}
  {{- with .Values.storage.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - {{ .Values.storage.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}