apiVersion: v1
kind: ConfigMap
metadata:
    name: mods-txt
    namespace: insurgency-sandstorm
data:
  Mods.txt: |
    150867; ISMCmod
    525547; Last Light
    1516914; ISMCresources
    98373; MoreAmmo
    564874; Zombies7
