apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mods
  namespace: insurgency-sandstorm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi