apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name  }}
  namespace: {{ .Release.namspace }}
  {{- with .Values.storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.storage.accessModes | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.storage.storageClassName | default "local-path" | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity | default "30Gi" | quote }}