apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-data
  namespace: minecraft
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi