apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.web.storage.name  }}
  namespace: {{ .Release.namspace }}
  {{- with .Values.web.storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.web.storage.accessModes | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.web.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.web.storage.capacity }}