{{- if .Values.hostpath.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.name }}
spec:
  capacity: 
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: {{ .Values.hostpath.path }}
{{- end }}    
