apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-server-data
  namespace: minecraft
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/home/core/minecraft-server"